import logging
from app.database.connection import get_db_connection
from app.agents.schemas import VendorSubscriptionModel

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def execute_model_onboarding(tenant_id: str, model_data: VendorSubscriptionModel) -> str:
    """
    Executes raw atomic inserts into the EAV database for a new vendor model.
    """
    try:
        with get_db_connection(tenant_id=tenant_id) as conn:
            with conn.cursor() as cursor:
                # 1. Iterate through products generated by the AI
                for product in model_data.products:
                    # Insert Product Entity
                    cursor.execute(
                        """
                        INSERT INTO products (tenant_id, sku, name, base_price)
                        VALUES (%s, %s, %s, %s)
                        RETURNING product_id;
                        """,
                        (tenant_id, product.sku, product.name, product.base_price)
                    )
                    product_id = cursor.fetchone()[0]

                    # 2. Iterate through the dynamic EAV attributes
                    for attr in product.attributes:
                        # Insert or Get Attribute ID
                        cursor.execute(
                            """
                            INSERT INTO attributes (tenant_id, attribute_name, data_type)
                            VALUES (%s, %s, %s)
                            ON CONFLICT (tenant_id, attribute_name) DO UPDATE 
                            SET attribute_name=EXCLUDED.attribute_name
                            RETURNING attribute_id;
                            """,
                            (tenant_id, attr.name, attr.data_type)
                        )
                        attribute_id = cursor.fetchone()[0]

                        # 3. Map the specific Value
                        cursor.execute(
                            """
                            INSERT INTO product_values (product_id, attribute_id, attribute_value)
                            VALUES (%s, %s, %s)
                            ON CONFLICT (product_id, attribute_id) DO NOTHING;
                            """,
                            (product_id, attribute_id, str(attr.value))
                        )
                
                # Commit the entire transaction atomically
                conn.commit()
                logger.info(f"Successfully onboarded model for tenant: {tenant_id}")
                return f"Success: Database schema populated for tenant {tenant_id}."
                
    except Exception as e:
        logger.error(f"Database transaction failed: {str(e)}")
        # The context manager pool automatically rolls back on unhandled exceptions,
        # but returning the error string allows LangGraph to attempt self-correction.
        return f"Error executing database inserts: {str(e)}"