from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import text
from fastapi import HTTPException, status

async def execute_raw_sql(db: AsyncSession, query_str: str, tenant_id: str):
    """
    Safely executes raw SQL queries generated by the agent against the PostgreSQL database.
    Performs safety checks against destructive database operations.
    """
    forbidden_keywords = ["DROP DATABASE", "TRUNCATE", "ALTER SYSTEM", "DROP TABLE"]
    upper_query = query_str.upper()
    
    if any(keyword in upper_query for keyword in forbidden_keywords):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Forbidden SQL operation detected. Destructive commands are strictly prohibited."
        )

    try:
        result = await db.execute(text(query_str), {"tenant_id": tenant_id})
        await db.commit()

        if result.returns_rows:
            rows = [dict(row._mapping) for row in result.fetchall()]
            return {
                "status": "success",
                "rows_affected": len(rows),
                "data": rows
            }

        return {
            "status": "success",
            "rows_affected": result.rowcount,
            "data": []
        }
    except Exception as e:
        await db.rollback()
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Database execution error: {str(e)}"
        )